#ifndef _COMMANDDBUS_CONFIG_H
#define _COMMANDDBUS_CONFIG_H

#cmakedefine COMMAND_DBUS_INTROSPECTION_FILE "@COMMAND_DBUS_INTROSPECTION_FILE@"
#cmakedefine LIBRARY_OUTPUT_PATH "@LIBRARY_OUTPUT_PATH@"

#endif /* _COMMANDDBUS_CONFIG_H */
