/*
* This file was generated by the CommonAPI Generators.
*
 *  Copyright (c) 2012 BMW
 *
 *  \author Aleksandar Donchev, aleksander.donchev@partner.bmw.de BMW 2013
 *
 *  \copyright
 *  Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction,
 *  including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so,
 *  subject to the following conditions:
 *  The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
 *  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
 *  IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR
 *  THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 *
 *  For further information see http://www.genivi.org/.
*/
#include "CommandInterfaceDBusStubAdapter.h"
#include <org/genivi/audiomanager/CommandInterface.h>

namespace org {
namespace genivi {
namespace audiomanager {

std::shared_ptr<CommonAPI::DBus::DBusStubAdapter> createCommandInterfaceDBusStubAdapter(
                   const std::string& commonApiAddress,
                   const std::string& interfaceName,
                   const std::string& busName,
                   const std::string& objectPath,
                   const std::shared_ptr<CommonAPI::DBus::DBusProxyConnection>& dbusProxyConnection,
                   const std::shared_ptr<CommonAPI::StubBase>& stubBase) {
    return std::make_shared<CommandInterfaceDBusStubAdapter>(commonApiAddress, interfaceName, busName, objectPath, dbusProxyConnection, stubBase);
}

__attribute__((constructor)) void registerCommandInterfaceDBusStubAdapter(void) {
    CommonAPI::DBus::DBusFactory::registerAdapterFactoryMethod(CommandInterface::getInterfaceId(),
                                                               &createCommandInterfaceDBusStubAdapter);
}

CommandInterfaceDBusStubAdapter::CommandInterfaceDBusStubAdapter(
        const std::string& commonApiAddress,
        const std::string& dbusInterfaceName,
        const std::string& dbusBusName,
        const std::string& dbusObjectPath,
        const std::shared_ptr<CommonAPI::DBus::DBusProxyConnection>& dbusConnection,
        const std::shared_ptr<CommonAPI::StubBase>& stub):
        CommandInterfaceDBusStubAdapterHelper(commonApiAddress, dbusInterfaceName, dbusBusName, dbusObjectPath, dbusConnection, std::dynamic_pointer_cast<CommandInterfaceStub>(stub)) {
}

const char* CommandInterfaceDBusStubAdapter::getMethodsDBusIntrospectionXmlData() const {
    return
        "<signal name=\"NumberOfMainConnectionsChanged\">\n"
        "</signal>\n"
        "<signal name=\"MainConnectionStateChanged\">\n"
            "<arg name=\"connectionID\" type=\"q\" />\n"
            "<arg name=\"connectionState\" type=\"i\" />\n"
        "</signal>\n"
        "<signal name=\"NumberOfSourceClassesChanged\">\n"
        "</signal>\n"
        "<signal name=\"SourceAdded\">\n"
            "<arg name=\"newSource\" type=\"(qs(ii)q)\" />\n"
        "</signal>\n"
        "<signal name=\"SourceRemoved\">\n"
            "<arg name=\"removedSourceID\" type=\"q\" />\n"
        "</signal>\n"
        "<signal name=\"MainSourceSoundPropertyChanged\">\n"
            "<arg name=\"sourceID\" type=\"q\" />\n"
            "<arg name=\"SoundProperty\" type=\"(in)\" />\n"
        "</signal>\n"
        "<signal name=\"SourceAvailabilityChanged\">\n"
            "<arg name=\"sourceID\" type=\"q\" />\n"
            "<arg name=\"availability\" type=\"(ii)\" />\n"
        "</signal>\n"
        "<signal name=\"NumberOfSinkClassesChanged\">\n"
        "</signal>\n"
        "<signal name=\"SinkAdded\">\n"
            "<arg name=\"newSink\" type=\"(qs(ii)niq)\" />\n"
        "</signal>\n"
        "<signal name=\"SinkRemoved\">\n"
            "<arg name=\"removedSinkID\" type=\"q\" />\n"
        "</signal>\n"
        "<signal name=\"MainSinkSoundPropertyChanged\">\n"
            "<arg name=\"sinkID\" type=\"q\" />\n"
            "<arg name=\"SoundProperty\" type=\"(in)\" />\n"
        "</signal>\n"
        "<signal name=\"SinkAvailabilityChanged\">\n"
            "<arg name=\"sinkID\" type=\"q\" />\n"
            "<arg name=\"availability\" type=\"(ii)\" />\n"
        "</signal>\n"
        "<signal name=\"VolumeChanged\">\n"
            "<arg name=\"sinkID\" type=\"q\" />\n"
            "<arg name=\"volume\" type=\"n\" />\n"
        "</signal>\n"
        "<signal name=\"SinkMuteStateChanged\">\n"
            "<arg name=\"sinkID\" type=\"q\" />\n"
            "<arg name=\"muteState\" type=\"i\" />\n"
        "</signal>\n"
        "<signal name=\"SystemPropertyChanged\">\n"
            "<arg name=\"SystemProperty\" type=\"(in)\" />\n"
        "</signal>\n"
        "<signal name=\"TimingInformationChanged\">\n"
            "<arg name=\"mainConnection\" type=\"q\" />\n"
            "<arg name=\"time\" type=\"n\" />\n"
        "</signal>\n"
        "<signal name=\"SinkUpdated\">\n"
            "<arg name=\"sinkID\" type=\"q\" />\n"
            "<arg name=\"sinkClassID\" type=\"q\" />\n"
            "<arg name=\"listMainSoundProperties\" type=\"a(in)\" />\n"
        "</signal>\n"
        "<signal name=\"SourceUpdated\">\n"
            "<arg name=\"sourceID\" type=\"q\" />\n"
            "<arg name=\"sourceClassID\" type=\"q\" />\n"
            "<arg name=\"listMainSoundProperties\" type=\"a(in)\" />\n"
        "</signal>\n"
        "<signal name=\"SinkNotification\">\n"
            "<arg name=\"sinkID\" type=\"q\" />\n"
            "<arg name=\"notification\" type=\"(in)\" />\n"
        "</signal>\n"
        "<signal name=\"SourceNotification\">\n"
            "<arg name=\"sourceID\" type=\"q\" />\n"
            "<arg name=\"notification\" type=\"(in)\" />\n"
        "</signal>\n"
        "<signal name=\"MainSinkNotificationConfigurationChanged\">\n"
            "<arg name=\"sinkID\" type=\"q\" />\n"
            "<arg name=\"mainNotificationConfiguration\" type=\"(iin)\" />\n"
        "</signal>\n"
        "<signal name=\"MainSourceNotificationConfigurationChanged\">\n"
            "<arg name=\"sourceID\" type=\"q\" />\n"
            "<arg name=\"mainNotificationConfiguration\" type=\"(iin)\" />\n"
        "</signal>\n"
        "<method name=\"Connect\">\n"
            "<arg name=\"sourceID\" type=\"q\" direction=\"in\" />\n"
            "<arg name=\"sinkID\" type=\"q\" direction=\"in\" />\n"
            "<arg name=\"result\" type=\"i\" direction=\"out\" />\n"
            "<arg name=\"mainConnectionID\" type=\"q\" direction=\"out\" />\n"
        "</method>\n"
        "<method name=\"Disconnect\">\n"
            "<arg name=\"mainConnectionID\" type=\"q\" direction=\"in\" />\n"
            "<arg name=\"result\" type=\"i\" direction=\"out\" />\n"
        "</method>\n"
        "<method name=\"SetVolume\">\n"
            "<arg name=\"sinkID\" type=\"q\" direction=\"in\" />\n"
            "<arg name=\"volume\" type=\"n\" direction=\"in\" />\n"
            "<arg name=\"result\" type=\"i\" direction=\"out\" />\n"
        "</method>\n"
        "<method name=\"VolumeStep\">\n"
            "<arg name=\"sinkID\" type=\"q\" direction=\"in\" />\n"
            "<arg name=\"volumeStep\" type=\"n\" direction=\"in\" />\n"
            "<arg name=\"result\" type=\"i\" direction=\"out\" />\n"
        "</method>\n"
        "<method name=\"SetSinkMuteState\">\n"
            "<arg name=\"sinkID\" type=\"q\" direction=\"in\" />\n"
            "<arg name=\"muteState\" type=\"i\" direction=\"in\" />\n"
            "<arg name=\"result\" type=\"i\" direction=\"out\" />\n"
        "</method>\n"
        "<method name=\"SetMainSinkSoundProperty\">\n"
            "<arg name=\"sinkID\" type=\"q\" direction=\"in\" />\n"
            "<arg name=\"soundProperty\" type=\"(in)\" direction=\"in\" />\n"
            "<arg name=\"result\" type=\"i\" direction=\"out\" />\n"
        "</method>\n"
        "<method name=\"SetMainSourceSoundProperty\">\n"
            "<arg name=\"sourceID\" type=\"q\" direction=\"in\" />\n"
            "<arg name=\"soundProperty\" type=\"(in)\" direction=\"in\" />\n"
            "<arg name=\"result\" type=\"i\" direction=\"out\" />\n"
        "</method>\n"
        "<method name=\"SetSystemProperty\">\n"
            "<arg name=\"soundProperty\" type=\"(in)\" direction=\"in\" />\n"
            "<arg name=\"result\" type=\"i\" direction=\"out\" />\n"
        "</method>\n"
        "<method name=\"GetListMainConnections\">\n"
            "<arg name=\"result\" type=\"i\" direction=\"out\" />\n"
            "<arg name=\"listConnections\" type=\"a(qqqni)\" direction=\"out\" />\n"
        "</method>\n"
        "<method name=\"GetListMainSinks\">\n"
            "<arg name=\"result\" type=\"i\" direction=\"out\" />\n"
            "<arg name=\"listMainSinks\" type=\"a(qs(ii)niq)\" direction=\"out\" />\n"
        "</method>\n"
        "<method name=\"GetListMainSources\">\n"
            "<arg name=\"result\" type=\"i\" direction=\"out\" />\n"
            "<arg name=\"listMainSources\" type=\"a(qs(ii)q)\" direction=\"out\" />\n"
        "</method>\n"
        "<method name=\"GetListMainSinkSoundProperties\">\n"
            "<arg name=\"sinkID\" type=\"q\" direction=\"in\" />\n"
            "<arg name=\"result\" type=\"i\" direction=\"out\" />\n"
            "<arg name=\"listSoundProperties\" type=\"a(in)\" direction=\"out\" />\n"
        "</method>\n"
        "<method name=\"GetListMainSourceSoundProperties\">\n"
            "<arg name=\"sourceID\" type=\"q\" direction=\"in\" />\n"
            "<arg name=\"result\" type=\"i\" direction=\"out\" />\n"
            "<arg name=\"listSourceProperties\" type=\"a(in)\" direction=\"out\" />\n"
        "</method>\n"
        "<method name=\"GetListSourceClasses\">\n"
            "<arg name=\"result\" type=\"i\" direction=\"out\" />\n"
            "<arg name=\"listSourceClasses\" type=\"a(qsa(in))\" direction=\"out\" />\n"
        "</method>\n"
        "<method name=\"GetListSinkClasses\">\n"
            "<arg name=\"result\" type=\"i\" direction=\"out\" />\n"
            "<arg name=\"listSinkClasses\" type=\"a(qsa(in))\" direction=\"out\" />\n"
        "</method>\n"
        "<method name=\"GetListSystemProperties\">\n"
            "<arg name=\"result\" type=\"i\" direction=\"out\" />\n"
            "<arg name=\"listSystemProperties\" type=\"a(in)\" direction=\"out\" />\n"
        "</method>\n"
        "<method name=\"GetTimingInformation\">\n"
            "<arg name=\"mainConnectionID\" type=\"q\" direction=\"in\" />\n"
            "<arg name=\"result\" type=\"i\" direction=\"out\" />\n"
            "<arg name=\"delay\" type=\"n\" direction=\"out\" />\n"
        "</method>\n"
    ;
}



static CommonAPI::DBus::DBusMethodWithReplyStubDispatcher<
    CommandInterfaceStub,
    std::tuple<CommandInterface::am_sourceID_t, CommandInterface::am_sinkID_t>,
    std::tuple<CommandInterface::am_Error_e, CommandInterface::am_mainConnectionID_t>
    > connectStubDispatcher(&CommandInterfaceStub::Connect, "iq");
static CommonAPI::DBus::DBusMethodWithReplyStubDispatcher<
    CommandInterfaceStub,
    std::tuple<CommandInterface::am_mainConnectionID_t>,
    std::tuple<CommandInterface::am_Error_e>
    > disconnectStubDispatcher(&CommandInterfaceStub::Disconnect, "i");
static CommonAPI::DBus::DBusMethodWithReplyStubDispatcher<
    CommandInterfaceStub,
    std::tuple<CommandInterface::am_sinkID_t, CommandInterface::am_mainVolume_t>,
    std::tuple<CommandInterface::am_Error_e>
    > setVolumeStubDispatcher(&CommandInterfaceStub::SetVolume, "i");
static CommonAPI::DBus::DBusMethodWithReplyStubDispatcher<
    CommandInterfaceStub,
    std::tuple<CommandInterface::am_sinkID_t, CommandInterface::am_mainVolume_t>,
    std::tuple<CommandInterface::am_Error_e>
    > volumeStepStubDispatcher(&CommandInterfaceStub::VolumeStep, "i");
static CommonAPI::DBus::DBusMethodWithReplyStubDispatcher<
    CommandInterfaceStub,
    std::tuple<CommandInterface::am_sinkID_t, CommandInterface::am_MuteState_e>,
    std::tuple<CommandInterface::am_Error_e>
    > setSinkMuteStateStubDispatcher(&CommandInterfaceStub::SetSinkMuteState, "i");
static CommonAPI::DBus::DBusMethodWithReplyStubDispatcher<
    CommandInterfaceStub,
    std::tuple<CommandInterface::am_sinkID_t, CommandInterface::am_MainSoundProperty_s>,
    std::tuple<CommandInterface::am_Error_e>
    > setMainSinkSoundPropertyStubDispatcher(&CommandInterfaceStub::SetMainSinkSoundProperty, "i");
static CommonAPI::DBus::DBusMethodWithReplyStubDispatcher<
    CommandInterfaceStub,
    std::tuple<CommandInterface::am_sourceID_t, CommandInterface::am_MainSoundProperty_s>,
    std::tuple<CommandInterface::am_Error_e>
    > setMainSourceSoundPropertyStubDispatcher(&CommandInterfaceStub::SetMainSourceSoundProperty, "i");
static CommonAPI::DBus::DBusMethodWithReplyStubDispatcher<
    CommandInterfaceStub,
    std::tuple<CommandInterface::am_SystemProperty_s>,
    std::tuple<CommandInterface::am_Error_e>
    > setSystemPropertyStubDispatcher(&CommandInterfaceStub::SetSystemProperty, "i");
static CommonAPI::DBus::DBusMethodWithReplyStubDispatcher<
    CommandInterfaceStub,
    std::tuple<>,
    std::tuple<CommandInterface::am_Error_e, CommandInterface::am_MainConnectionType_l>
    > getListMainConnectionsStubDispatcher(&CommandInterfaceStub::GetListMainConnections, "ia(qqqni)");
static CommonAPI::DBus::DBusMethodWithReplyStubDispatcher<
    CommandInterfaceStub,
    std::tuple<>,
    std::tuple<CommandInterface::am_Error_e, CommandInterface::am_SinkType_l>
    > getListMainSinksStubDispatcher(&CommandInterfaceStub::GetListMainSinks, "ia(qs(ii)niq)");
static CommonAPI::DBus::DBusMethodWithReplyStubDispatcher<
    CommandInterfaceStub,
    std::tuple<>,
    std::tuple<CommandInterface::am_Error_e, CommandInterface::am_SourceType_l>
    > getListMainSourcesStubDispatcher(&CommandInterfaceStub::GetListMainSources, "ia(qs(ii)q)");
static CommonAPI::DBus::DBusMethodWithReplyStubDispatcher<
    CommandInterfaceStub,
    std::tuple<CommandInterface::am_sinkID_t>,
    std::tuple<CommandInterface::am_Error_e, CommandInterface::am_MainSoundProperty_l>
    > getListMainSinkSoundPropertiesStubDispatcher(&CommandInterfaceStub::GetListMainSinkSoundProperties, "ia(in)");
static CommonAPI::DBus::DBusMethodWithReplyStubDispatcher<
    CommandInterfaceStub,
    std::tuple<CommandInterface::am_sourceID_t>,
    std::tuple<CommandInterface::am_Error_e, CommandInterface::am_MainSoundProperty_l>
    > getListMainSourceSoundPropertiesStubDispatcher(&CommandInterfaceStub::GetListMainSourceSoundProperties, "ia(in)");
static CommonAPI::DBus::DBusMethodWithReplyStubDispatcher<
    CommandInterfaceStub,
    std::tuple<>,
    std::tuple<CommandInterface::am_Error_e, CommandInterface::am_SourceClass_l>
    > getListSourceClassesStubDispatcher(&CommandInterfaceStub::GetListSourceClasses, "ia(qsa(in))");
static CommonAPI::DBus::DBusMethodWithReplyStubDispatcher<
    CommandInterfaceStub,
    std::tuple<>,
    std::tuple<CommandInterface::am_Error_e, CommandInterface::am_SinkClass_l>
    > getListSinkClassesStubDispatcher(&CommandInterfaceStub::GetListSinkClasses, "ia(qsa(in))");
static CommonAPI::DBus::DBusMethodWithReplyStubDispatcher<
    CommandInterfaceStub,
    std::tuple<>,
    std::tuple<CommandInterface::am_Error_e, CommandInterface::am_SystemProperty_l>
    > getListSystemPropertiesStubDispatcher(&CommandInterfaceStub::GetListSystemProperties, "ia(in)");
static CommonAPI::DBus::DBusMethodWithReplyStubDispatcher<
    CommandInterfaceStub,
    std::tuple<CommandInterface::am_mainConnectionID_t>,
    std::tuple<CommandInterface::am_Error_e, CommandInterface::am_timeSync_t>
    > getTimingInformationStubDispatcher(&CommandInterfaceStub::GetTimingInformation, "in");


void CommandInterfaceDBusStubAdapter::fireNumberOfMainConnectionsChangedEvent() {
    CommonAPI::DBus::DBusStubSignalHelper<CommonAPI::DBus::DBusSerializableArguments<>>
            ::sendSignal(
                *this,
                "NumberOfMainConnectionsChanged",
                ""
        );
}
void CommandInterfaceDBusStubAdapter::fireMainConnectionStateChangedEvent(const CommandInterface::am_mainConnectionID_t& connectionID, const CommandInterface::am_ConnectionState_e& connectionState) {
    CommonAPI::DBus::DBusStubSignalHelper<CommonAPI::DBus::DBusSerializableArguments<CommandInterface::am_mainConnectionID_t, CommandInterface::am_ConnectionState_e>>
            ::sendSignal(
                *this,
                "MainConnectionStateChanged",
                "qi",
                connectionID, connectionState
        );
}
void CommandInterfaceDBusStubAdapter::fireNumberOfSourceClassesChangedEvent() {
    CommonAPI::DBus::DBusStubSignalHelper<CommonAPI::DBus::DBusSerializableArguments<>>
            ::sendSignal(
                *this,
                "NumberOfSourceClassesChanged",
                ""
        );
}
void CommandInterfaceDBusStubAdapter::fireSourceAddedEvent(const CommandInterface::am_SourceType_s& newSource) {
    CommonAPI::DBus::DBusStubSignalHelper<CommonAPI::DBus::DBusSerializableArguments<CommandInterface::am_SourceType_s>>
            ::sendSignal(
                *this,
                "SourceAdded",
                "(qs(ii)q)",
                newSource
        );
}
void CommandInterfaceDBusStubAdapter::fireSourceRemovedEvent(const CommandInterface::am_sourceID_t& removedSourceID) {
    CommonAPI::DBus::DBusStubSignalHelper<CommonAPI::DBus::DBusSerializableArguments<CommandInterface::am_sourceID_t>>
            ::sendSignal(
                *this,
                "SourceRemoved",
                "q",
                removedSourceID
        );
}
void CommandInterfaceDBusStubAdapter::fireMainSourceSoundPropertyChangedEvent(const CommandInterface::am_sourceID_t& sourceID, const CommandInterface::am_MainSoundProperty_s& SoundProperty) {
    CommonAPI::DBus::DBusStubSignalHelper<CommonAPI::DBus::DBusSerializableArguments<CommandInterface::am_sourceID_t, CommandInterface::am_MainSoundProperty_s>>
            ::sendSignal(
                *this,
                "MainSourceSoundPropertyChanged",
                "q(in)",
                sourceID, SoundProperty
        );
}
void CommandInterfaceDBusStubAdapter::fireSourceAvailabilityChangedEvent(const CommandInterface::am_sourceID_t& sourceID, const CommandInterface::am_Availability_s& availability) {
    CommonAPI::DBus::DBusStubSignalHelper<CommonAPI::DBus::DBusSerializableArguments<CommandInterface::am_sourceID_t, CommandInterface::am_Availability_s>>
            ::sendSignal(
                *this,
                "SourceAvailabilityChanged",
                "q(ii)",
                sourceID, availability
        );
}
void CommandInterfaceDBusStubAdapter::fireNumberOfSinkClassesChangedEvent() {
    CommonAPI::DBus::DBusStubSignalHelper<CommonAPI::DBus::DBusSerializableArguments<>>
            ::sendSignal(
                *this,
                "NumberOfSinkClassesChanged",
                ""
        );
}
void CommandInterfaceDBusStubAdapter::fireSinkAddedEvent(const CommandInterface::am_SinkType_s& newSink) {
    CommonAPI::DBus::DBusStubSignalHelper<CommonAPI::DBus::DBusSerializableArguments<CommandInterface::am_SinkType_s>>
            ::sendSignal(
                *this,
                "SinkAdded",
                "(qs(ii)niq)",
                newSink
        );
}
void CommandInterfaceDBusStubAdapter::fireSinkRemovedEvent(const CommandInterface::am_sinkID_t& removedSinkID) {
    CommonAPI::DBus::DBusStubSignalHelper<CommonAPI::DBus::DBusSerializableArguments<CommandInterface::am_sinkID_t>>
            ::sendSignal(
                *this,
                "SinkRemoved",
                "q",
                removedSinkID
        );
}
void CommandInterfaceDBusStubAdapter::fireMainSinkSoundPropertyChangedEvent(const CommandInterface::am_sinkID_t& sinkID, const CommandInterface::am_MainSoundProperty_s& SoundProperty) {
    CommonAPI::DBus::DBusStubSignalHelper<CommonAPI::DBus::DBusSerializableArguments<CommandInterface::am_sinkID_t, CommandInterface::am_MainSoundProperty_s>>
            ::sendSignal(
                *this,
                "MainSinkSoundPropertyChanged",
                "q(in)",
                sinkID, SoundProperty
        );
}
void CommandInterfaceDBusStubAdapter::fireSinkAvailabilityChangedEvent(const CommandInterface::am_sinkID_t& sinkID, const CommandInterface::am_Availability_s& availability) {
    CommonAPI::DBus::DBusStubSignalHelper<CommonAPI::DBus::DBusSerializableArguments<CommandInterface::am_sinkID_t, CommandInterface::am_Availability_s>>
            ::sendSignal(
                *this,
                "SinkAvailabilityChanged",
                "q(ii)",
                sinkID, availability
        );
}
void CommandInterfaceDBusStubAdapter::fireVolumeChangedEvent(const CommandInterface::am_sinkID_t& sinkID, const CommandInterface::am_mainVolume_t& volume) {
    CommonAPI::DBus::DBusStubSignalHelper<CommonAPI::DBus::DBusSerializableArguments<CommandInterface::am_sinkID_t, CommandInterface::am_mainVolume_t>>
            ::sendSignal(
                *this,
                "VolumeChanged",
                "qn",
                sinkID, volume
        );
}
void CommandInterfaceDBusStubAdapter::fireSinkMuteStateChangedEvent(const CommandInterface::am_sinkID_t& sinkID, const CommandInterface::am_MuteState_e& muteState) {
    CommonAPI::DBus::DBusStubSignalHelper<CommonAPI::DBus::DBusSerializableArguments<CommandInterface::am_sinkID_t, CommandInterface::am_MuteState_e>>
            ::sendSignal(
                *this,
                "SinkMuteStateChanged",
                "qi",
                sinkID, muteState
        );
}
void CommandInterfaceDBusStubAdapter::fireSystemPropertyChangedEvent(const CommandInterface::am_SystemProperty_s& SystemProperty) {
    CommonAPI::DBus::DBusStubSignalHelper<CommonAPI::DBus::DBusSerializableArguments<CommandInterface::am_SystemProperty_s>>
            ::sendSignal(
                *this,
                "SystemPropertyChanged",
                "(in)",
                SystemProperty
        );
}
void CommandInterfaceDBusStubAdapter::fireTimingInformationChangedEvent(const CommandInterface::am_mainConnectionID_t& mainConnection, const CommandInterface::am_timeSync_t& time) {
    CommonAPI::DBus::DBusStubSignalHelper<CommonAPI::DBus::DBusSerializableArguments<CommandInterface::am_mainConnectionID_t, CommandInterface::am_timeSync_t>>
            ::sendSignal(
                *this,
                "TimingInformationChanged",
                "qn",
                mainConnection, time
        );
}
void CommandInterfaceDBusStubAdapter::fireSinkUpdatedEvent(const CommandInterface::am_sinkID_t& sinkID, const CommandInterface::am_sinkClass_t& sinkClassID, const CommandInterface::am_MainSoundProperty_l& listMainSoundProperties) {
    CommonAPI::DBus::DBusStubSignalHelper<CommonAPI::DBus::DBusSerializableArguments<CommandInterface::am_sinkID_t, CommandInterface::am_sinkClass_t, CommandInterface::am_MainSoundProperty_l>>
            ::sendSignal(
                *this,
                "SinkUpdated",
                "qqa(in)",
                sinkID, sinkClassID, listMainSoundProperties
        );
}
void CommandInterfaceDBusStubAdapter::fireSourceUpdatedEvent(const CommandInterface::am_sourceID_t& sourceID, const CommandInterface::am_sourceClass_t& sourceClassID, const CommandInterface::am_MainSoundProperty_l& listMainSoundProperties) {
    CommonAPI::DBus::DBusStubSignalHelper<CommonAPI::DBus::DBusSerializableArguments<CommandInterface::am_sourceID_t, CommandInterface::am_sourceClass_t, CommandInterface::am_MainSoundProperty_l>>
            ::sendSignal(
                *this,
                "SourceUpdated",
                "qqa(in)",
                sourceID, sourceClassID, listMainSoundProperties
        );
}
void CommandInterfaceDBusStubAdapter::fireSinkNotificationEvent(const CommandInterface::am_sinkID_t& sinkID, const CommandInterface::am_NotificationPayload_s& notification) {
    CommonAPI::DBus::DBusStubSignalHelper<CommonAPI::DBus::DBusSerializableArguments<CommandInterface::am_sinkID_t, CommandInterface::am_NotificationPayload_s>>
            ::sendSignal(
                *this,
                "SinkNotification",
                "q(in)",
                sinkID, notification
        );
}
void CommandInterfaceDBusStubAdapter::fireSourceNotificationEvent(const CommandInterface::am_sourceID_t& sourceID, const CommandInterface::am_NotificationPayload_s& notification) {
    CommonAPI::DBus::DBusStubSignalHelper<CommonAPI::DBus::DBusSerializableArguments<CommandInterface::am_sourceID_t, CommandInterface::am_NotificationPayload_s>>
            ::sendSignal(
                *this,
                "SourceNotification",
                "q(in)",
                sourceID, notification
        );
}
void CommandInterfaceDBusStubAdapter::fireMainSinkNotificationConfigurationChangedEvent(const CommandInterface::am_sinkID_t& sinkID, const am::am_NotificationConfiguration_s& mainNotificationConfiguration) {
    CommonAPI::DBus::DBusStubSignalHelper<CommonAPI::DBus::DBusSerializableArguments<CommandInterface::am_sinkID_t, am::am_NotificationConfiguration_s>>
            ::sendSignal(
                *this,
                "MainSinkNotificationConfigurationChanged",
                "q(iin)",
                sinkID, mainNotificationConfiguration
        );
}
void CommandInterfaceDBusStubAdapter::fireMainSourceNotificationConfigurationChangedEvent(const CommandInterface::am_sourceID_t& sourceID, const am::am_NotificationConfiguration_s& mainNotificationConfiguration) {
    CommonAPI::DBus::DBusStubSignalHelper<CommonAPI::DBus::DBusSerializableArguments<CommandInterface::am_sourceID_t, am::am_NotificationConfiguration_s>>
            ::sendSignal(
                *this,
                "MainSourceNotificationConfigurationChanged",
                "q(iin)",
                sourceID, mainNotificationConfiguration
        );
}

} // namespace audiomanager
} // namespace genivi
} // namespace org

template<>
const org::genivi::audiomanager::CommandInterfaceDBusStubAdapterHelper::StubDispatcherTable org::genivi::audiomanager::CommandInterfaceDBusStubAdapterHelper::stubDispatcherTable_ = {
    { { "Connect", "qq" }, &org::genivi::audiomanager::connectStubDispatcher },
    { { "Disconnect", "q" }, &org::genivi::audiomanager::disconnectStubDispatcher },
    { { "SetVolume", "qn" }, &org::genivi::audiomanager::setVolumeStubDispatcher },
    { { "VolumeStep", "qn" }, &org::genivi::audiomanager::volumeStepStubDispatcher },
    { { "SetSinkMuteState", "qi" }, &org::genivi::audiomanager::setSinkMuteStateStubDispatcher },
    { { "SetMainSinkSoundProperty", "q(in)" }, &org::genivi::audiomanager::setMainSinkSoundPropertyStubDispatcher },
    { { "SetMainSourceSoundProperty", "q(in)" }, &org::genivi::audiomanager::setMainSourceSoundPropertyStubDispatcher },
    { { "SetSystemProperty", "(in)" }, &org::genivi::audiomanager::setSystemPropertyStubDispatcher },
    { { "GetListMainConnections", "" }, &org::genivi::audiomanager::getListMainConnectionsStubDispatcher },
    { { "GetListMainSinks", "" }, &org::genivi::audiomanager::getListMainSinksStubDispatcher },
    { { "GetListMainSources", "" }, &org::genivi::audiomanager::getListMainSourcesStubDispatcher },
    { { "GetListMainSinkSoundProperties", "q" }, &org::genivi::audiomanager::getListMainSinkSoundPropertiesStubDispatcher },
    { { "GetListMainSourceSoundProperties", "q" }, &org::genivi::audiomanager::getListMainSourceSoundPropertiesStubDispatcher },
    { { "GetListSourceClasses", "" }, &org::genivi::audiomanager::getListSourceClassesStubDispatcher },
    { { "GetListSinkClasses", "" }, &org::genivi::audiomanager::getListSinkClassesStubDispatcher },
    { { "GetListSystemProperties", "" }, &org::genivi::audiomanager::getListSystemPropertiesStubDispatcher },
    { { "GetTimingInformation", "q" }, &org::genivi::audiomanager::getTimingInformationStubDispatcher }
};
