#ifndef _ROUTINGDBUS_CONFIG_H
#define _ROUTINGDBUS_CONFIG_H

#cmakedefine CAPI_SENDER_INTERFACE "@CAPI_SENDER_INTERFACE@"
#cmakedefine CAPI_SENDER_INSTANCE "@CAPI_SENDER_INSTANCE@"
#cmakedefine CAPI_SENDER_PATH "@CAPI_SENDER_PATH@"

#endif /* _ROUTINGDBUS_CONFIG_H */
