/*
* This file was generated by the CommonAPI Generators.
*
 * Copyright (C) 2013, BMW AG
 *
 * \author Christian Linke, christian.linke@bmw.de BMW 2012,2013
*/
#ifndef ORG_GENIVI_AM_Routing_Control_Observer_H_
#define ORG_GENIVI_AM_Routing_Control_Observer_H_



#define COMMONAPI_INTERNAL_COMPILATION

#include <CommonAPI/types.h>

#undef COMMONAPI_INTERNAL_COMPILATION

namespace org {
namespace genivi {
namespace am {

class RoutingControlObserver {
 public:
    virtual ~RoutingControlObserver() { }

    static inline const char* getInterfaceId();
    static inline CommonAPI::Version getInterfaceVersion();
};

const char* RoutingControlObserver::getInterfaceId() {
    return "org.genivi.am.RoutingControlObserver";
}

CommonAPI::Version RoutingControlObserver::getInterfaceVersion() {
    return CommonAPI::Version(0, 1);
}


} // namespace am
} // namespace genivi
} // namespace org

namespace CommonAPI {

}


namespace std {
    //hashes for types
    
    //hashes for error types
}

#endif // ORG_GENIVI_AM_Routing_Control_Observer_H_
