/**
 * Copyright (C) 2011, BMW AG
 *
 * GeniviAudioMananger DbusPlugin
 *
 * \file CAmCommandSender.cpp
 *
 * \date 20-Oct-2011 3:42:04 PM
 * \author Christian Mueller (christian.ei.mueller@bmw.de)
 *
 * \section License
 * GNU Lesser General Public License, version 2.1, with special exception (GENIVI clause)
 * Copyright (C) 2011, BMW AG Christian Mueller  Christian.ei.mueller@bmw.de
 *
 * This program is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License, version 2.1, as published by the Free Software Foundation.
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License, version 2.1, for more details.
 * You should have received a copy of the GNU Lesser General Public License, version 2.1, along with this program; if not, see <http://www.gnu.org/licenses/lgpl-2.1.html>.
 * Note that the copyright holders assume that the GNU Lesser General Public License, version 2.1, may also be applicable to programs even in cases in which the program is not a library in the technical sense.
 * Linking AudioManager statically or dynamically with other modules is making a combined work based on AudioManager. You may license such other modules under the GNU Lesser General Public License, version 2.1. If you do not want to license your linked modules under the GNU Lesser General Public License, version 2.1, you may use the program under the following exception.
 * As a special exception, the copyright holders of AudioManager give you permission to combine AudioManager with software programs or libraries that are released under any license unless such a combination is not permitted by the license of such a software program or library. You may copy and distribute such a system following the terms of the GNU Lesser General Public License, version 2.1, including this special exception, for AudioManager and the licenses of the other code concerned.
 * Note that people who make modified versions of AudioManager are not obligated to grant this special exception for their modified versions; it is their choice whether to do so. The GNU Lesser General Public License, version 2.1, gives permission to release a modified version without this exception; this exception also makes it possible to release a modified version which carries forward this exception.
 *
 * THIS CODE HAS BEEN GENERATED BY ENTERPRISE ARCHITECT GENIVI MODEL. PLEASE CHANGE ONLY IN ENTERPRISE ARCHITECT AND GENERATE AGAIN
 */

#include "CAmCommandSenderDbus.h"
#include <algorithm>
#include <string>
#include <vector>
#include <cassert>
#include <set>
#include "CAmDbusMessageHandler.h"
#include "shared/CAmDltWrapper.h"
#include "shared/CAmDbusWrapper.h"


DLT_DECLARE_CONTEXT(commandDbus)

using namespace am;

/**
 * factory for plugin loading
 */
extern "C" IAmCommandSend* PluginCommandInterfaceDbusFactory()
{
    return (new CAmCommandSenderDbus());
}

/**
 * destroy instance of commandSendInterface
 */
extern "C" void destroyRoutingPluginInterfaceDbus(IAmCommandSend* commandSendInterface)
{
    delete commandSendInterface;
}

CAmCommandSenderDbus::CAmCommandSenderDbus() :
        mCAmDbusMessageHandler(), //
        mIAmCommandReceiverShadow(), //
        mpCAmDbusWrapper(NULL), //
        mpIAmCommandReceive(NULL), //
        mReady(false)
{
    CAmDltWrapper::instance()->registerContext(commandDbus, "DBP", "DBus Plugin");
    log(&commandDbus, DLT_LOG_INFO, "DbusCommandSender constructor called");
}

CAmCommandSenderDbus::~CAmCommandSenderDbus()
{
    log(&commandDbus, DLT_LOG_INFO, "DbusCommandSender destructed");
    CAmDltWrapper::instance()->unregisterContext(commandDbus);
}

am_Error_e CAmCommandSenderDbus::startupInterface(IAmCommandReceive* commandreceiveinterface)
{
    log(&commandDbus, DLT_LOG_INFO, "startupInterface called");

    mpIAmCommandReceive = commandreceiveinterface;
    mIAmCommandReceiverShadow.setCommandReceiver(mpIAmCommandReceive);
    mpIAmCommandReceive->getDBusConnectionWrapper(mpCAmDbusWrapper);
    assert(mpCAmDbusWrapper!=NULL);
    DBusConnection * connection;
    mpCAmDbusWrapper->getDBusConnection(connection);
    assert(connection!=NULL);
    mCAmDbusMessageHandler.setDBusConnection(connection);
    return (E_OK);
}

void CAmCommandSenderDbus::setCommandReady(const uint16_t handle)
{
    //todo:implement handle handling
    log(&commandDbus, DLT_LOG_INFO, "cbCommunicationReady called");
    mReady = true;
    mpIAmCommandReceive->confirmCommandReady(handle);
}

void CAmCommandSenderDbus::setCommandRundown(const uint16_t handle)
{
    log(&commandDbus, DLT_LOG_INFO, "cbCommunicationRundown called");
    mReady = false;
    mpIAmCommandReceive->confirmCommandRundown(handle);
    /**
     * todo: implement DbusCommandSender::cbCommunicationRundown()
     */
}

void CAmCommandSenderDbus::cbNewMainConnection(const am_MainConnectionType_s mainConnection)
{
    (void)mainConnection;
    //todo: change xml and interface to differetiate between new connection and removed one
    log(&commandDbus, DLT_LOG_INFO, "cbNumberOfMainConnectionsChanged called");

    if (mReady)
    {
        mCAmDbusMessageHandler.initSignal(std::string(MY_NODE), std::string("NumberOfMainConnectionsChanged"));
        mCAmDbusMessageHandler.sendMessage();
    }
}

void CAmCommandSenderDbus::cbRemovedMainConnection(const am_mainConnectionID_t mainConnection)
{
    (void)mainConnection;
//todo: change xml and interface to differetiate between new connection and removed one
    log(&commandDbus, DLT_LOG_INFO, "cbNumberOfMainConnectionsChanged called");

    if (mReady)
    {
        mCAmDbusMessageHandler.initSignal(std::string(MY_NODE), std::string("NumberOfMainConnectionsChanged"));
        mCAmDbusMessageHandler.sendMessage();
    }
}

void CAmCommandSenderDbus::cbNewSink(const am_SinkType_s& sink)
{
    log(&commandDbus, DLT_LOG_INFO, "cbNewSink called");

    if (mReady)
    {
        mCAmDbusMessageHandler.initSignal(std::string(MY_NODE), "SinkAdded");
        mCAmDbusMessageHandler.append(sink);

        log(&commandDbus, DLT_LOG_INFO, "send signal SinkAdded");
        mCAmDbusMessageHandler.sendMessage();
    }
}

void CAmCommandSenderDbus::cbRemovedSink(const am_sinkID_t sinkID)
{
    //todo: check if this really works!
    log(&commandDbus, DLT_LOG_INFO, "cbRemovedSink called");

    if (mReady)
    {
        mCAmDbusMessageHandler.initSignal(std::string(MY_NODE), "SinkRemoved");
        mCAmDbusMessageHandler.append(sinkID);

        log(&commandDbus, DLT_LOG_INFO, "send signal SinkAdded");
        mCAmDbusMessageHandler.sendMessage();
    }
}

void CAmCommandSenderDbus::cbNewSource(const am_SourceType_s& source)
{
    log(&commandDbus, DLT_LOG_INFO, "cbNumberOfSourcesChanged called");

    if (mReady)
    {
        mCAmDbusMessageHandler.initSignal(std::string(MY_NODE), "SourceAdded");
        mCAmDbusMessageHandler.append(source);

        log(&commandDbus, DLT_LOG_INFO, "send signal SourceAdded");
        mCAmDbusMessageHandler.sendMessage();
    }
}

void am::CAmCommandSenderDbus::cbRemovedSource(const am_sourceID_t source)
{
    if (mReady)
    {
        mCAmDbusMessageHandler.initSignal(std::string(MY_NODE), "SourceRemoved");
        mCAmDbusMessageHandler.append(source);

        log(&commandDbus, DLT_LOG_INFO, "send signal SourceRemoved");

        mCAmDbusMessageHandler.sendMessage();
    }
}

void CAmCommandSenderDbus::cbNumberOfSinkClassesChanged()
{
    log(&commandDbus, DLT_LOG_INFO, "cbNumberOfSinkClassesChanged called");

    if (mReady)
    {
        mCAmDbusMessageHandler.initSignal(std::string(MY_NODE), std::string("NumberOfSinkClassesChanged"));
        mCAmDbusMessageHandler.sendMessage();
    }
}

void CAmCommandSenderDbus::cbNumberOfSourceClassesChanged()
{
    log(&commandDbus, DLT_LOG_INFO, "cbNumberOfSourceClassesChanged called");

    if (mReady)
    {
        mCAmDbusMessageHandler.initSignal(std::string(MY_NODE), std::string("NumberOfSourceClassesChanged"));
        mCAmDbusMessageHandler.sendMessage();
    }
}

void CAmCommandSenderDbus::cbMainConnectionStateChanged(const am_mainConnectionID_t connectionID, const am_ConnectionState_e connectionState)
{
    log(&commandDbus, DLT_LOG_INFO, "cbMainConnectionStateChanged called, connectionID=", connectionID, "connectionState=", connectionState);

    if (mReady)
    {
        mCAmDbusMessageHandler.initSignal(std::string(MY_NODE), std::string("MainConnectionStateChanged"));
        mCAmDbusMessageHandler.append((dbus_uint16_t) connectionID);
        mCAmDbusMessageHandler.append((dbus_int16_t) connectionState);
        mCAmDbusMessageHandler.sendMessage();
    }
}

void CAmCommandSenderDbus::cbMainSinkSoundPropertyChanged(const am_sinkID_t sinkID, const am_MainSoundProperty_s & soundProperty)
{
    log(&commandDbus, DLT_LOG_INFO, "cbMainSinkSoundPropertyChanged called, sinkID", sinkID, "SoundProperty.type", soundProperty.type, "SoundProperty.value", soundProperty.value);

    if (mReady)
    {
        mCAmDbusMessageHandler.initSignal(std::string(MY_NODE), std::string("MainSinkSoundPropertyChanged"));
        mCAmDbusMessageHandler.append((dbus_uint16_t) sinkID);
        mCAmDbusMessageHandler.append(soundProperty);
        mCAmDbusMessageHandler.sendMessage();
    }
}

void CAmCommandSenderDbus::cbMainSourceSoundPropertyChanged(const am_sourceID_t sourceID, const am_MainSoundProperty_s & SoundProperty)
{
    log(&commandDbus, DLT_LOG_INFO, "cbMainSourceSoundPropertyChanged called, sourceID", sourceID, "SoundProperty.type", SoundProperty.type, "SoundProperty.value", SoundProperty.value);

    if (mReady)
    {
        mCAmDbusMessageHandler.initSignal(std::string(MY_NODE), std::string("MainSourceSoundPropertyChanged"));
        mCAmDbusMessageHandler.append((dbus_uint16_t) sourceID);
        mCAmDbusMessageHandler.append(SoundProperty);
        mCAmDbusMessageHandler.sendMessage();
    }
}

void CAmCommandSenderDbus::cbSinkAvailabilityChanged(const am_sinkID_t sinkID, const am_Availability_s & availability)
{
    log(&commandDbus, DLT_LOG_INFO, "cbSinkAvailabilityChanged called, sinkID", sinkID, "availability.availability", availability.availability, "SoundProperty.reason", availability.availabilityReason);

    if (mReady)
    {
        mCAmDbusMessageHandler.initSignal(std::string(MY_NODE), std::string("SinkAvailabilityChanged"));
        mCAmDbusMessageHandler.append((dbus_uint16_t) sinkID);
        mCAmDbusMessageHandler.append(availability);
        mCAmDbusMessageHandler.sendMessage();
    }
}

void CAmCommandSenderDbus::cbSourceAvailabilityChanged(const am_sourceID_t sourceID, const am_Availability_s & availability)
{
    log(&commandDbus, DLT_LOG_INFO, "cbSourceAvailabilityChanged called, sourceID", sourceID, "availability.availability", availability.availability, "SoundProperty.reason", availability.availabilityReason);

    if (mReady)
    {
        mCAmDbusMessageHandler.initSignal(std::string(MY_NODE), std::string("SourceAvailabilityChanged"));
        mCAmDbusMessageHandler.append((dbus_uint16_t) sourceID);
        mCAmDbusMessageHandler.append(availability);
        mCAmDbusMessageHandler.sendMessage();
    }
}

void CAmCommandSenderDbus::cbVolumeChanged(const am_sinkID_t sinkID, const am_mainVolume_t volume)
{
    log(&commandDbus, DLT_LOG_INFO, "cbVolumeChanged called, sinkID", sinkID, "volume", volume);

    if (mReady)
    {
        mCAmDbusMessageHandler.initSignal(std::string(MY_NODE), std::string("VolumeChanged"));
        mCAmDbusMessageHandler.append((dbus_uint16_t) sinkID);
        mCAmDbusMessageHandler.append((dbus_int16_t) volume);
        mCAmDbusMessageHandler.sendMessage();
    }
}

void CAmCommandSenderDbus::cbSinkMuteStateChanged(const am_sinkID_t sinkID, const am_MuteState_e muteState)
{
    log(&commandDbus, DLT_LOG_INFO, "cbSinkMuteStateChanged called, sinkID", sinkID, "muteState", muteState);

    if (mReady)
    {
        mCAmDbusMessageHandler.initSignal(std::string(MY_NODE), std::string("SinkMuteStateChanged"));
        mCAmDbusMessageHandler.append((dbus_uint16_t) sinkID);
        mCAmDbusMessageHandler.append((dbus_int16_t) muteState);
        mCAmDbusMessageHandler.sendMessage();
    }
}

void CAmCommandSenderDbus::cbSystemPropertyChanged(const am_SystemProperty_s & SystemProperty)
{
    log(&commandDbus, DLT_LOG_INFO, "cbSystemPropertyChanged called, SystemProperty.type", SystemProperty.type, "SystemProperty.value", SystemProperty.value);

    if (mReady)
    {
        mCAmDbusMessageHandler.initSignal(std::string(MY_NODE), std::string("SystemPropertyChanged"));
        mCAmDbusMessageHandler.append(SystemProperty);
        mCAmDbusMessageHandler.sendMessage();
    }
}

void am::CAmCommandSenderDbus::cbTimingInformationChanged(const am_mainConnectionID_t mainConnectionID, const am_timeSync_t time)
{
    log(&commandDbus, DLT_LOG_INFO, "cbTimingInformationChanged called, mainConnectionID=", mainConnectionID, "time=", time);

    if (mReady)
    {
        mCAmDbusMessageHandler.initSignal(std::string(MY_NODE), std::string("TimingInformationChanged"));
        mCAmDbusMessageHandler.append((dbus_uint16_t) mainConnectionID);
        mCAmDbusMessageHandler.append((dbus_int16_t) time);
        mCAmDbusMessageHandler.sendMessage();
    }
}

void CAmCommandSenderDbus::getInterfaceVersion(std::string & version) const
{
    version = CommandSendVersion;
}

