/**
* Copyright (C) 2011, BMW AG
*
* GeniviAudioMananger AudioManagerDaemon
*
* \file MockInterfaces.h
*
* \date 20-Oct-2011 3:42:04 PM
* \author Christian Mueller (christian.ei.mueller@bmw.de)
*
* \section License
* GNU Lesser General Public License, version 2.1, with special exception (GENIVI clause)
* Copyright (C) 2011, BMW AG Christian Mueller  Christian.ei.mueller@bmw.de
*
* This program is free software; you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License, version 2.1, as published by the Free Software Foundation.
* This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License, version 2.1, for more details.
* You should have received a copy of the GNU Lesser General Public License, version 2.1, along with this program; if not, see <http://www.gnu.org/licenses/lgpl-2.1.html>.
* Note that the copyright holders assume that the GNU Lesser General Public License, version 2.1, may also be applicable to programs even in cases in which the program is not a library in the technical sense.
* Linking AudioManager statically or dynamically with other modules is making a combined work based on AudioManager. You may license such other modules under the GNU Lesser General Public License, version 2.1. If you do not want to license your linked modules under the GNU Lesser General Public License, version 2.1, you may use the program under the following exception.
* As a special exception, the copyright holders of AudioManager give you permission to combine AudioManager with software programs or libraries that are released under any license unless such a combination is not permitted by the license of such a software program or library. You may copy and distribute such a system following the terms of the GNU Lesser General Public License, version 2.1, including this special exception, for AudioManager and the licenses of the other code concerned.
* Note that people who make modified versions of AudioManager are not obligated to grant this special exception for their modified versions; it is their choice whether to do so. The GNU Lesser General Public License, version 2.1, gives permission to release a modified version without this exception; this exception also makes it possible to release a modified version which carries forward this exception.
*
* THIS CODE HAS BEEN GENERATED BY ENTERPRISE ARCHITECT GENIVI MODEL. PLEASE CHANGE ONLY IN ENTERPRISE ARCHITECT AND GENERATE AGAIN
*/

#ifndef MOCKCOMMANDINTERFACE_H_
#define MOCKCOMMANDINTERFACE_H_

#include "command/IAmCommandSend.h"
#include <gtest/gtest.h>
#include <gmock/gmock.h>

namespace am {

class MockIAmCommandSend : public IAmCommandSend {
 public:
  MOCK_METHOD1(startupInterface,
      am_Error_e(IAmCommandReceive* commandreceiveinterface));
  MOCK_METHOD1(setCommandReady,
      void(const uint16_t handle));
  MOCK_METHOD1(setCommandRundown,
      void(const uint16_t handle));
  MOCK_METHOD1(cbNewMainConnection,
      void(const am_MainConnectionType_s mainConnection));
  MOCK_METHOD1(cbRemovedMainConnection,
      void(const am_mainConnectionID_t mainConnection));
  MOCK_METHOD1(cbNewSink,
      void(const am_SinkType_s& sink));
  MOCK_METHOD1(cbRemovedSink,
      void(const am_sinkID_t sinkID));
  MOCK_METHOD1(cbNewSource,
      void(const am_SourceType_s& source));
  MOCK_METHOD1(cbRemovedSource,
      void(const am_sourceID_t source));
  MOCK_METHOD0(cbNumberOfSinkClassesChanged,
      void());
  MOCK_METHOD0(cbNumberOfSourceClassesChanged,
      void());
  MOCK_METHOD2(cbMainConnectionStateChanged,
      void(const am_mainConnectionID_t connectionID, const am_ConnectionState_e connectionState));
  MOCK_METHOD2(cbMainSinkSoundPropertyChanged,
      void(const am_sinkID_t sinkID, const am_MainSoundProperty_s& soundProperty));
  MOCK_METHOD2(cbMainSourceSoundPropertyChanged,
      void(const am_sourceID_t sourceID, const am_MainSoundProperty_s& soundProperty));
  MOCK_METHOD2(cbSinkAvailabilityChanged,
      void(const am_sinkID_t sinkID, const am_Availability_s& availability));
  MOCK_METHOD2(cbSourceAvailabilityChanged,
      void(const am_sourceID_t sourceID, const am_Availability_s& availability));
  MOCK_METHOD2(cbVolumeChanged,
      void(const am_sinkID_t sinkID, const am_mainVolume_t volume));
  MOCK_METHOD2(cbSinkMuteStateChanged,
      void(const am_sinkID_t sinkID, const am_MuteState_e muteState));
  MOCK_METHOD1(cbSystemPropertyChanged,
      void(const am_SystemProperty_s& systemProperty));
  MOCK_METHOD2(cbTimingInformationChanged,
      void(const am_mainConnectionID_t mainConnectionID, const am_timeSync_t time));
  MOCK_CONST_METHOD1(getInterfaceVersion,
      void(std::string& version));
};

}  // namespace am
#endif /* MOCKCOMMANDINTERFACE_H_ */
