#ifndef _CONFIG_H
#define _CONFIG_H

#cmakedefine DAEMONVERSION "@DAEMONVERSION@"

#cmakedefine WITH_DBUS_WRAPPER
#cmakedefine WITH_SOCKETHANDLER_LOOP 
#cmakedefine WITH_SIMPLEDBUS_LOOP 
#cmakedefine WITH_PPOLL

#cmakedefine DEFAULT_PLUGIN_COMMAND_DIR "@DEFAULT_PLUGIN_COMMAND_DIR@"
#cmakedefine DEFAULT_PLUGIN_ROUTING_DIR "@DEFAULT_PLUGIN_ROUTING_DIR@"
#cmakedefine CONTROLLER_PLUGIN "@CONTROLLER_PLUGIN@"

#cmakedefine DBUS_SERVICE_PREFIX "@DBUS_SERVICE_PREFIX@"
#cmakedefine DBUS_SERVICE_OBJECT_PATH "@DBUS_SERVICE_OBJECT_PATH@"

#cmakedefine INTROSPECTION_COMMAND_XML_FILE "@INTROSPECTION_COMMAND_XML_FILE@"

#endif /* _CONFIG_H */
