#ifndef _CONFIG_H
#define _CONFIG_H

#cmakedefine DAEMONVERSION "@DAEMONVERSION@"

#cmakedefine WITH_DBUS_WRAPPER
#cmakedefine WITH_DLT
#cmakedefine WITH_TELNET
#cmakedefine GLIB_DBUS_TYPES_TOLERANT
#cmakedefine WITH_SYSTEMD_WATCHDOG
#cmakedefine SYSTEMD_FOUND

#cmakedefine DEFAULT_PLUGIN_COMMAND_DIR "@DEFAULT_PLUGIN_COMMAND_DIR@"
#cmakedefine DEFAULT_PLUGIN_ROUTING_DIR "@DEFAULT_PLUGIN_ROUTING_DIR@"
#cmakedefine CONTROLLER_PLUGIN "@CONTROLLER_PLUGIN@"

#cmakedefine DEFAULT_TELNETPORT @DEFAULT_TELNETPORT@
#cmakedefine MAX_TELNETCONNECTIONS @MAX_TELNETCONNECTIONS@

#cmakedefine DBUS_SERVICE_PREFIX "@DBUS_SERVICE_PREFIX@"
#cmakedefine DBUS_SERVICE_OBJECT_PATH "@DBUS_SERVICE_OBJECT_PATH@"

#cmakedefine EXECUTABLE_OUTPUT_PATH "@EXECUTABLE_OUTPUT_PATH@" 

#endif /* _CONFIG_H */
