#Can be changed via passing -DVERSION="XXX" to cmake
if (NOT DEFINED VERSION)
    FILE(READ "VERSION" DAEMONVERSION)
else (NOT DEFINED VERSION)
    set (DAEMONVERSION "${VERSION}")
endif (NOT DEFINED VERSION)

message(STATUS "Build Version ${DAEMONVERSION}${EXTRAVERSIONINFO}")

execute_process(COMMAND git log --pretty=short WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR} 
                OUTPUT_FILE ${CMAKE_CURRENT_SOURCE_DIR}/CHANGELOG)

