    
   macro(GET_COMMAND_INTERFACE_VERSION INCLUDE_FOLDER)   
    
        FILE(READ "${INCLUDE_FOLDER}/command/IAmCommandSend.h" VERSION_BUFFER LIMIT 6000)
        STRING(REGEX MATCH "CommandSendVersion*.[^0-9]*[0-9].[0-9]*[0-9]" LIB_COMMAND_INTERFACE_VERSION ${VERSION_BUFFER})
        STRING(REGEX REPLACE "CommandSendVersion*.." "" LIB_COMMAND_INTERFACE_VERSION ${LIB_COMMAND_INTERFACE_VERSION})
   
   endmacro(GET_COMMAND_INTERFACE_VERSION INCLUDE_FOLDER)    
   
   macro(GET_ROUTING_INTERFACE_VERSION INCLUDE_FOLDER)   
    
        FILE(READ "${INCLUDE_FOLDER}/routing/IAmRoutingSend.h" VERSION_BUFFER LIMIT 6000)
        STRING(REGEX MATCH "RoutingSendVersion*.[^0-9]*[0-9].[0-9]*[0-9]" LIB_ROUTING_INTERFACE_VERSION ${VERSION_BUFFER})
        STRING(REGEX REPLACE "RoutingSendVersion*.." "" LIB_ROUTING_INTERFACE_VERSION ${LIB_ROUTING_INTERFACE_VERSION})
   
   endmacro(GET_ROUTING_INTERFACE_VERSION INCLUDE_FOLDER)    
   
   macro(GET_CONTROL_INTERFACE_VERSION INCLUDE_FOLDER)   
    
        FILE(READ "${INCLUDE_FOLDER}/control/IAmControlSend.h" VERSION_BUFFER LIMIT 6000)
        STRING(REGEX MATCH "ControlSendVersion*.[^0-9]*[0-9].[0-9]*[0-9]" LIB_CONTROL_INTERFACE_VERSION ${VERSION_BUFFER})
        STRING(REGEX REPLACE "ControlSendVersion*.." "" LIB_CONTROL_INTERFACE_VERSION ${LIB_CONTROL_INTERFACE_VERSION})
   
   endmacro(GET_CONTROL_INTERFACE_VERSION INCLUDE_FOLDER)   