    
   macro(GET_COMMAND_INTERFACE_VERSION INCLUDE_FOLDER)   
    
        FILE(READ "${INCLUDE_FOLDER}/IAmCommand.h" VERSION_BUFFER LIMIT 6000)
        STRING(REGEX MATCH "CommandVersion*.[^0-9]*[0-9].[0-9]*[0-9]" LIB_COMMAND_INTERFACE_VERSION ${VERSION_BUFFER})
        STRING(REGEX REPLACE "CommandVersion*.." "" LIB_COMMAND_INTERFACE_VERSION ${LIB_COMMAND_INTERFACE_VERSION})
   
   endmacro(GET_COMMAND_INTERFACE_VERSION INCLUDE_FOLDER)    
   
   macro(GET_ROUTING_INTERFACE_VERSION INCLUDE_FOLDER)   
    
        FILE(READ "${INCLUDE_FOLDER}/IAmRouting.h" VERSION_BUFFER LIMIT 6000)
        STRING(REGEX MATCH "RoutingVersion*.[^0-9]*[0-9].[0-9]*[0-9]" LIB_ROUTING_INTERFACE_VERSION ${VERSION_BUFFER})
        STRING(REGEX REPLACE "RoutingVersion*.." "" LIB_ROUTING_INTERFACE_VERSION ${LIB_ROUTING_INTERFACE_VERSION})
   
   endmacro(GET_ROUTING_INTERFACE_VERSION INCLUDE_FOLDER)    
   
   macro(GET_CONTROL_INTERFACE_VERSION INCLUDE_FOLDER)   
    
        FILE(READ "${INCLUDE_FOLDER}/IAmControl.h" VERSION_BUFFER LIMIT 6000)
        STRING(REGEX MATCH "ControlVersion*.[^0-9]*[0-9].[0-9]*[0-9]" LIB_CONTROL_INTERFACE_VERSION ${VERSION_BUFFER})
        STRING(REGEX REPLACE "ControlVersion*.." "" LIB_CONTROL_INTERFACE_VERSION ${LIB_CONTROL_INTERFACE_VERSION})
   
   endmacro(GET_CONTROL_INTERFACE_VERSION INCLUDE_FOLDER)   
